### ISSUE TITLE
What about poorman instead of dplyr ? 

### ISSUE THREAD

**Issue by lrnv** [moodymudskipper/safejoin#38]
Hi, 

Instead of using dplyr::join, could we use poorman::join ? See [there](https://github.com/nathaneastwood/poorman). Would remove a huge dependency from the package

**Comment by lrnv** [comment]
nevermind, thisis not implemented yet.

**Comment by moodymudskipper** [comment]
I like dplyr's api, and fuzzyjoin depends on dplyr too so I don't know if I could really get rid of the dependency.

This package had not been given much attention, though for some reason this last week it's been starred a few times, so I might get back to work on it, maybe I can make a safemerge sister package that would use the base R merge instead.

**Comment by lrnv** [comment]
Well, thanks for reoppening ! I'd love to see that happening; Dependencies make code break sooner that you want and drive me crazy these times..

**Comment by moodymudskipper** [comment]
Apologies @lrnv but this is unlikely to happen, at least in the short term. Dev is stopped for {safejoin} and continues in {powerjoin}, and {powerjoin} borrows code from dplyr which depends on a fair amount of packages...

{poorman} join funs are wrappers around merge and I needed to modify the merging algo itself to be efficient, I could do it with {dplyr}
