### ISSUE TITLE
dplyr has changed the behavior of na_matches

### ISSUE THREAD

**Issue by karldw** [moodymudskipper/safejoin#40]
Thanks for the useful package! I noticed that the `na_matches` configuration can be a little funny. By default, dplyr doesn't set it anymore, and if it's set, dplyr raises a warning.

Here's an example:
``` r
library(safejoin)

x <- safe_left_join(mtcars, mtcars, check="")
#> Error: `na_matches` must be a character vector.

library(dplyr, quietly = TRUE, warn.conflicts = FALSE)
x <- safe_left_join(mtcars, mtcars, check="")
#> Error: `na_matches` must be a character vector.

pkgconfig::set_config("dplyr::na_matches" = "na")

x <- safe_left_join(mtcars, mtcars, check="")
#> Warning: `dplyr::na_matches` pkgconfig options is now ignored.
#> * Please set `na_matches` directly.
```

Here's the relevant dplyr code:
https://github.com/tidyverse/dplyr/blob/0bea3e80a876cceb9e179ef3a64d94103c350c41/R/join.r#L390

**Comment by moodymudskipper** [comment]
Thanks a lot for reporting, this is inconvenient indeed! I'll fix this asap

**Comment by karldw** [comment]
Would it help if I submitted a PR? The fix I'm imagining is set the `na_matches` default to `c("na", "never")` and add a `na_matches <- match.arg(na_matches)` call in the `safe_join` function.

**Comment by moodymudskipper** [comment]
Thanks Karl, it was just that indeed, with the equivalent update in `eat`,  it should work now!

**Comment by karldw** [comment]
That works perfectly, thanks!
